### ISSUE TITLE
Unable to connect from host to host

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [stefanha/nc-vsock#1]
I tried to listen vsock on host and also connect from host, I got `connect: Invalid argument` error

> Terminal 1:
> nc-vock -l 9003
> 
> Terminal 2:
> nc-vsock 2 9003
> connect: Invalid argument

am i missing anything?

**Comment by stefanha** [comment]
Loopback on the host has only been supported since Linux v5.6.  Is your host kernel recent?

Does lsmod on the host show that the vhost_vsock kernel module is loaded?

**Comment by KarthikNedunchezhiyan** [comment]
tnx @stefanha after upgrading the kernel to v5.6 I am able to use loopback on host `VMADDR_CID_LOCAL`
