### ISSUE TITLE
stdin closing does not output any pending data from remote

### ISSUE THREAD

**Issue by darkyp** [stefanha/nc-vsock#4]
As the title describes - example:
echo test | nc-vsock 2 130

echo emits the text and is done effectively closing STDIN for nc-vsock which in turn exits the main_loop. However remote_fd might still be present and sending data. 

I resolved it by excluding STDIN from the select once it indicated an error and continue the loop till remote_fd is alive.

**Comment by stefanha** [comment]
Thanks for reporting this. nc-vsock is no longer maintained because the more widely available nmap ncat tool supports AF_VSOCK with the `--vsock` option. Please use ncat instead.

I will update the repo to make it clearer that nc-vsock is no longer maintained.
